#include "utils.h"
#include <cerrno>
#include <csignal>
#include <cstdint>
#include <cstdlib>
#include <iostream>
#include <signal.h>
#include <stdexcept>
#include <string>
#include <sys/syslog.h>
#include <unistd.h>
